name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create config directory
        run: mkdir -p config

      - name: Create Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > config/serviceAccountKey.json

      - name: Run linting
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Run Firebase connection test
        run: npm run test-firebase

      - name: Run TypeScript Firebase tests
        run: |
          npx ts-node tests/firebase/test-burnkit-core.ts
          npx ts-node tests/firebase/test-burnkit-subcollections.ts
          npx ts-node tests/firebase/test-burnkit-realtime.ts

  publish:
    name: Publish to NPM
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update package version
        run: npm version ${{ steps.extract_version.outputs.VERSION }} --no-git-tag-version

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
